### ISSUE TITLE
Field rendering in article causes broken "/p>"

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#101]
I used this syntax to render a field in the content:
`<p>{{#fields alias=rezeptbild}}<br />{{{value}}}<br />{{/fields}}</p>`

![bildschirmfoto 2016-06-01 um 21 10 38](https://cloud.githubusercontent.com/assets/828371/15722307/53607386-283d-11e6-941d-5da5449eb01b.png)

The `<p>` are added automatically by tinymce in the standard configuration

but for some reason it renders like that:
![bildschirmfoto 2016-06-01 um 21 09 26](https://cloud.githubusercontent.com/assets/828371/15722277/36ca35b8-283d-11e6-85c6-5e99308b4a4c.png)
![bildschirmfoto 2016-06-01 um 21 10 16](https://cloud.githubusercontent.com/assets/828371/15722291/4467241a-283d-11e6-8b68-b17b790a706d.png)

**Comment by laoneo** [comment]
With JCE it should work better as tinymce is not very good in that part.

**Comment by laoneo** [comment]
I guess the only option is to disable auto formating in tinymce.

**Comment by coolcat-creations** [comment]
But it´s the core and standard setting...

**Comment by zero-24** [comment]
Hmm so we have the same issue with writing articles? I meam the not closing p tag?

As the html code looks good in the editor? Why does com_fields don't show it like the html code above?

**Comment by laoneo** [comment]
Tinymce does some auto formating and breaks the source code. This is the only reason I have for it. Ah wait is the output then broken or what?

**Comment by coolcat-creations** [comment]
The output it broken, yeah...

**Comment by coolcat-creations** [comment]
Is this fixed?

**Comment by laoneo** [comment]
Yes, with this commit https://github.com/joomla-projects/custom-fields/commit/2dc40ae56d4f5517bc59b7fdec08d378995afa0c
