### ISSUE TITLE
Switch Field-type of existing field

### ISSUE THREAD

**Issue by MacNiels** [joomla-projects/custom-fields#103]
### Steps to reproduce the issue

Make a new (custom) field
#### Expected result

The field is made (example: text)
#### Actual result

a text field
#### Additional comments

I want to change this field in something else like a image or textarea.
Now you have to delete or disable the field and make new one. 
Would be nice if it handles like the menu manager when you define what you want to display.

**Comment by laoneo** [comment]
A type can't be changed because of the settings it has.
