### ISSUE TITLE
Custom Fields in Contact Form

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#110]
Would be nice to have custom Fields in the Contact Form. Would be very useful!
:-)

**Comment by laoneo** [comment]
Please test the patch of #111.

**Comment by coolcat-creations** [comment]
How to? Just copy paste the code from the patch? Thanks for advise!

**Comment by laoneo** [comment]
Yes, or download it from the branch and make a full new installation from that url https://github.com/joomla-projects/custom-fields/tree/feature/contact.

**Comment by laoneo** [comment]
I'm reopening this issue as it addresses a different feature request than what is done in #111.

**Comment by laoneo** [comment]
How should then the fields being processed? I guess you don't want additional fields for the contact itself as what is done in PR #111?

**Comment by coolcat-creations** [comment]
The additional fields are ok, they could be useful too - but more important i think is also the possibility to have input fields in Frontend for the contact form. Maybe just a checkbox or a switch to define if it´s an input or an output field and the possibility to define how the field is processed. Either something to define that the input is used for the receipient or is there even a mail template i can override ?

**Comment by laoneo** [comment]
Please test the PR of #115. Closing it again.
