### ISSUE TITLE
Permissions options from Field Groups are missing

### ISSUE THREAD

**Issue by hugofmsilva** [joomla-projects/custom-fields#116]
#### Steps to reproduce the issue
1. Create new Field Group
2. Click in "Permissions" tab
3. Options are missing
#### Expected result

Show permissions options
#### Actual result

Missing permissions options
#### System information (as much as possible)

Latest git version
![missing_options](https://cloud.githubusercontent.com/assets/4529320/16051698/b5d675d6-3258-11e6-85be-162802b94e92.png)

**Comment by laoneo** [comment]
Can you please test PR #157, which should fix the issue here. Closing this one as we have now a PR for this one.
