### ISSUE TITLE
Should we ship the Mustache not better as system lib than the component lib?

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/custom-fields#12]
see: https://github.com/joomla-projects/custom-fields/tree/custom-fields/administrator/components/com_fields/libraries/Mustache

Corrently this lib is shipped with com_fileds but i guess it would be better to have it in the core lib folder? What do you mean?

**Comment by wilsonge** [comment]
If we are going to use it then we should import it with composer (https://packagist.org/packages/mustache/mustache) but honestly it seems like massive overkill for the use case here and this might be one of the few times where in house code is better. I need to do more research into the flexibility it's giving us for the size of package we are getting. Maybe composer importing it is a good starting block and we can then decide if we are going to keep it completely or not

**Comment by laoneo** [comment]
I would welcome to have one standard in Joomla to template small stuff, especially that can then be used in content plugins. There is no need then to do some regex kung fu which looks different for every content plugin. The only drawback mustache has, that it is not possible to paremeterize a block, I had to do a little workaround https://github.com/joomla-projects/custom-fields/blob/custom-fields/plugins/system/fields/fields.php#L393. Perhaps there is a better way to accomplish that.

**Comment by wilsonge** [comment]
Move to load moustache through composer in #43 - but keep this issue open so we can decide on whether to actually use it or some other system :)

**Comment by brianteeman** [comment]
I am really not in favour of us having another templating engine. It doesnt matter to me if this is easier or better. What matters to me is that we are introducing a new way fo doing stuff but only in this one small part of Joomla

**Comment by wilsonge** [comment]
I agree - I think we probably should be removing it - but I want to experiment with what Moustache provides - for now let's put it where it should be (loaded through composer) and we'll try and figure out what it's giving us here and whether it's something that's better off doing "in house"

**Comment by brianteeman** [comment]
Even if it is better than what we have currently UNLESS we move everything
to mustache then I am against it being used

On 1 April 2016 at 22:49, George Wilson notifications@github.com wrote:

> I agree - I think we probably should be removing it - but I want to
> experiment with what Moustache provides - for now let's put it where it
> should be (loaded through composer) and we'll try and figure out what it's
> giving us here and whether it's something that's better off doing "in house"
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/12#issuecomment-204561888

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
What for a template engine do we have now? Every content plugin developer does it's own way. As far as I know we don't have a template engine at all.

**Comment by b2z** [comment]
> As far as I know we don't have a template engine at all.

Yes we do it in clean PHP way - JLayout. Let's continue to use it and leave 3rd party engines to Joomla! 4.

**Comment by laoneo** [comment]
I guess you are mixing stuff here. We don't use JLayouts in content plugins. Mustache is used in com_fields to fill the description part of an article with fields information. It means you can write something like

```
<ol>{{#fields}}<li>{{label}}: <b class="{{render_class}}">{{{value}}}</b></li>{{/fields}}
```

in the description of an article and it will populate an ordered list with the fields labels and values. It takes away the burden for the content plugin developers to mess around with some regex and takes care of escaping stuff correctly. The use case here is totally different than for JLayouts.

If you want to see some code, here it will be used https://github.com/joomla-projects/custom-fields/blob/custom-fields/plugins/system/fields/fields.php#L470.

**Comment by b2z** [comment]
Do you mean that content plugin developers should use Mustache to render custom fields? Sorry I did not read properly the docs for DPFields yet, so can you give me an example of code for 3rd party plugin using custom fields? Thank you :) 

Just want to understand what we can do here in order to drop Mustache.

**Comment by laoneo** [comment]
They must NOT but they CAN. With mustache, we have a simple template engine which takes away the repetitive work every content plugin developer does by parsing the description and do some magic regex replacement.
More documentation can be found here https://github.com/bobthecow/mustache.php. Perhaps I'm just to lazy to just reinvent the wheel all the time :smile:

**Comment by pbwebdev** [comment]
Would love to see it stay as a loaded extra via composer. 

The type of developer that would be using moustache would be comfortable with composer in my opinion.

**Comment by Bakual** [comment]
I'm with Brian here. Mustache is certainly a good template engine, but if there are no plans to use it outside of com_fields, it doesn't make sense to integrate it in core.
We have JLayouts and regular laout files to render things which will do that job just fine. And yes, layouts have been used for content plugins already (see https://github.com/joomla-projects/custom-fields/blob/custom-fields/plugins/content/pagenavigation/tmpl/default.php).

Please lets not introduce yet another way to render things.

**Comment by chrisdavenport** [comment]
Mustache is being used to parse the "tags" in the content that will be replaced by the custom field variables.  It's like parsing and replacing {loadposition some-module-position}.  For the loadposition plugin we've just used some basic regex, but Mustache supports a richer syntax that is useful for custom fields.

It would be nice to have a standard syntax which is core-supported, so that other plugins can make use of the same syntax/parser if they want to.  I'm just not sure if that should be Mustache or not.  Note that the custom fields code already does some pre-processing to handle parameters, which points to a weakness in Mustache anyway.  I started looking at the alternatives but didn't get vary far.

We could write our own parser, but we need to be careful to avoid inventing a new wheel if we don't need to.  Ideally, I think we should parse the content using our chosen parser, then render the output using JLayouts.  In other words, separate parsing from rendering.

**Comment by Bakual** [comment]
Of course if the plan is to implement such a parsing engine into core, then Mustache may be a good choice (as it's a well known and documented library without to much overhead). But then we should start rewriting things to use it instead of using Regex.
If it's only going to be com_fields that is using it with no plans to use it elsewhere, then I think it ends up being bloatware in our system.

> In other words, separate parsing from rendering.

If we're going to implement Mustache, it looks like a bit of a waste to me to still use our own rendering system. Mustache is a template engine, not a parsing library. If we only need some parsing for a content plugin, then honestly a regex is simpler. It's not like the needed regex are very complex there.

**Comment by laoneo** [comment]
> But then we should start rewriting things to use it instead of using Regex.

That would be then step 2. I guess many people would replace their regex with the simpler mustache code.

> I started looking at the alternatives but didn't get vary far.

Me neither, couldn't find any alternative which is simple to use and supports the functionality we need.

Again, this is not to replace JLayouts, the layout is the "description" of the article or whatever is passed on _onContentPrepare_.

**Comment by zero-24** [comment]
FYI: https://volunteer.joomla.org/reports/245-plt-meeting-after-j-and-beyond-2016

> Joomla 3.7.x status (Chris)
> 
> Custom Fields development is taking place at: https://github.com/joomla-projects/custom-fields/ . The PLT agreed the moustache rendering engine should be removed and replaced with a simple parser.

**Comment by chrisdavenport** [comment]
I think the next step is to define the syntax that we want/need to be supported.  That could look like the Mustache syntax but doesn't need to.  The vision here is to define something that could be used more widely than just custom fields.  Keep it simple, but cover everything we need.

Given a clear, documented syntax, I think it should be quite simple to then write a parser that will parse it.

**Comment by phproberto** [comment]
Goals should be:
- Do not reinvent the wheel.
- Something that can be used for JS & PHP.
- Something that is fully tested and we don't have to maintain.

So you end with Twig & Mustache. Personally I'd go for Twig.

**Comment by chrisdavenport** [comment]
The problem with Twig and Mustache is that they bring a great deal of bloat for what is basically pretty simple.  And Mustache doesn't even cover all the requirements for custom fields and needs to be extended!  If you know of a package that matches what we need without the bloat, then please let us know.

**Comment by mbabker** [comment]
Pulling in any template rendering engine without refactoring all of Joomla to standardize on it is going to be bloat.  So essentially it boils down to re-invent the wheel, accept the bloat, or commit to a long term restructure of the entire rendering system to use the pulled in engine so it's less bloaty.

**Comment by laoneo** [comment]
As I agree with @chrisdavenport, my concern is to find somebody who volunteers to write that library. I'm not a regex expert, so I guess I' not of much help on that, that's why I'v used mustache :see_no_evil: . What I suggest in that case is to remove the functionality completely in com_fields and to start a new project.

**Comment by coolcat-creations** [comment]
why isnt it possible to use a similar syntax and similar system (editorbutton) like including a module into the article?

**Comment by chrisdavenport** [comment]
> why isnt it possible to use a similar syntax and similar system (editorbutton) like including a module into the article? 

It is possible.  We just need to define the syntax.  I don't think we need anything like the complexity of Mustache's syntax.  Given a simple syntax, writing the parser should be straightforward and I'm happy to help with that if no-one else steps forward.  It might not even involve regex, which is slow and best avoided if possible.

Ideally, I'd like to have a standardised parser which, in the case of custom fields, generates a parse tree that can be rendered using JLayouts.  I haven't studied the code enough to know how easy or hard that would be.

Perhaps @laoneo can describe the minimal syntax that would actually be required by custom fields?  That would be a good starting point.  We can then discuss it and come to an agreed syntax that we need to support.

**Comment by coolcat-creations** [comment]
And if it will be possible to use the same syntax in the php override it would be awesome :-) I think you would need just: 
{fields alias getvalue} {fields alias getlabel} {fields alias rawoutput} {fields alias gettext} {fields alias renderfield}
and i dont know if its possible to use if and foreach on the overrides with such syntax?

**Comment by Bakual** [comment]
If we could use a syntax that follows the one we generally use for plugins (eg what @designbengel wrote), that would be great :+1:

**Comment by laoneo** [comment]
But then I will remove in com_fields the content plugin functionality completely to not delay the custom fields project. If the parser is ready soon enough, we can add it then in 3.7, otherwise we will ship it on a later point. @chrisdavenport would that work for you?

**Comment by laoneo** [comment]
> {fields alias getvalue} {fields alias getlabel} {fields alias rawoutput} {fields alias gettext} {fields alias renderfield}

So no looping trough the fields? Mustache provides a simple syntax to loop trough an array as described here https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#sections.

**Comment by coolcat-creations** [comment]
you mean looping through all fields? think thats not needed in custom layouts / overrides. but the possibility to use if clauses and foreach is of course needed...

**Comment by laoneo** [comment]
We are talking here about the content plugin event https://docs.joomla.org/Plugin/Events/Content#onContentPrepare. Means it parses the description of the article and replaces some tags with custom fields data. No layout is involved here.

**Comment by coolcat-creations** [comment]
For me defining how the output will be rendered = layouting - No?

**Comment by laoneo** [comment]
I'v removed Mustache from the core for [now](41bd1f62df2d3f708a73c5d8cb0d3b9342827390). Content plugins and per field output is not working anymore. I'v opened a new PR #135 which reverts the change. This PR is intended as the starting point for a new common parser functionality for content plugins (if somebody has time to do it). At least we don't hold back the custom fields project. Hope this procedure is ok for all.

**Comment by laoneo** [comment]
I'm closing this issue. Further comments should be done on the pull request #135. Thanks for the feedback so far, really appreciated!
