### ISSUE TITLE
Remain tab open on save

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#123]
Open a Fieldtab in user. 
Click save.
the view changes to account details.

Select another Tab and click on save.
The tab remains active.

I think the fieldtab should have the same behaviour?

**Comment by laoneo** [comment]
The only thing I could reproduce is when I assigned a user field to a new group. Then the active tab didn't remain and it started from the account details. But when I have selected a field group and hit save the same tab is active again.

**Comment by laoneo** [comment]
Do you still have that issue? If ye, can you add some kind of screencast how you get the error?

**Comment by coolcat-creations** [comment]
On the lastest merge i cannot reproduce it also. so i close the issue :)
