### ISSUE TITLE
Fields appear also as Fields in the Fieldgroup itself

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#125]
Fields appear also as Fields in the Field Group itself.
i think thats not intended, is it?
![bildschirmfoto 2016-06-14 um 22 20 57](https://cloud.githubusercontent.com/assets/828371/16060165/5279ef7e-327e-11e6-9b69-f63d06940080.png)

**Comment by laoneo** [comment]
This is a duplicate of #112.
