### ISSUE TITLE
Feature Request: Assign Fieldgroups to Usergroups

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#127]
It´s not yet possible to assign a Fieldgroup to be shown just to a specific Usergroup.

**Comment by laoneo** [comment]
You have to work with access levels.

**Comment by coolcat-creations** [comment]
Ok, seems the ACL is not working yet then (issue #116)

**Comment by laoneo** [comment]
Access and permissions are different things. You have requested view access or?

**Comment by coolcat-creations** [comment]
Example: 
I create a Usergroup "Members" and want to assign all fields from the Field Group "Memberinformations" to be shown just for Userprofiles which are assigned to the Usergroup "Members" - How to achieve this?

**Comment by laoneo** [comment]
As I said. Joomla uses access levels for it. Every field has an access level you can set. It will be then only displayed for them.

**Comment by coolcat-creations** [comment]
Sorry it´s not what i mean. If i set the Access Level to Registered it´s of course shown at the Superadministrator... but it should be just assigned to the specific group, so access is not that what i mean. And also for complete Fieldgroups if possible?

**Comment by laoneo** [comment]
Access level are the construct of Joomla for view access. So it doesn't make sense to implement here differently.

**Comment by coolcat-creations** [comment]
Sorry i need help with the setup, can you help me?
1) I created a Usergroup "Members" with parent "Registered"
2) created the Userlevel "Members" and just Membergroup has access to it
3) created a Fieldgroup "Members" and set access to "Members"
4) created a field and assigned it to "Members" - just to be sure i also set access to "Members"
5) The Field-Group (Tab) is still shown in the superadministrator profile and not only in the assigned usergroup

**Comment by laoneo** [comment]
Ok, now I get it. Till now, field groups have been only for grouping purposes as tabs. No ACL inheritance was done. Can do that and would make sense. The only question I have is when the field has a different access level than the group, who wins? I'm not sure, but with articles, the access level of the article wins :unamused: .

**Comment by coolcat-creations** [comment]
I see the Field Group as a "Container" if the container is not accessible by the group it´s completely hidden. 

But it´s really tricky.

For example as a superuser i want to see this Field-Group just in the Profiles which are assigned to "Members" but not in my profile. 

Also if i´m not part of the usergroup "Members" i need view/write access as superuser that would be then the permission tab, yes?

**Comment by laoneo** [comment]
This was fixed with #153. There is also a PR #157 open for the permission problem.
