### ISSUE TITLE
Missing language Strings in Frontend Edit (Fields)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#129]
Following strings appear as not translated in the frontend:
- JSELECT, JCLEAR
- JOPTION_DO_NOT_USE

**Comment by laoneo** [comment]
Can you post a screenshot please where you see them.

**Comment by coolcat-creations** [comment]
![bildschirmfoto 2016-06-16 um 00 16 50](https://cloud.githubusercontent.com/assets/828371/16099263/abea47c8-3357-11e6-813b-c1267182a41d.png)
![bildschirmfoto 2016-06-16 um 00 16 45](https://cloud.githubusercontent.com/assets/828371/16099264/abefce14-3357-11e6-93c2-9f60cd7f2efd.png)
