### ISSUE TITLE
Gallery Field Bugs ?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#130]
- By using - Use Default - in the gallery field i get the Error Message „Invalid Field Directory“
- If i select the header directory, i have just - None Selected - as option in the dropdown of this field,
- If i select "sampledata" (has subfolders) i get also - None Selected - 
- Errormessage JFolder: :folder: Path is not a folder. Path: Applications/MAMP/htdocs/customfields_contact/sampledata

**Comment by laoneo** [comment]
I'v removed the gallery field as we rely now solely on the available form fields. See PR #104 for more information. If such a gallery field is needed, then a new issue should be opened against the CMS repo.
