### ISSUE TITLE
Suggestion: Combine all text input Fields into 1

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#131]
Idea to shorten the list of Fields a bit:

1) Rename Text into "Textinput"
2) Add the possibiliy to validate email, phone, url (in fact you change the fieldtype then but these are also just textinput fields with a special feature/validation

**Comment by laoneo** [comment]
But they exist as JFormFields with a documentation for them, eg. E-Mail https://docs.joomla.org/Email_form_field_type.

**Comment by coolcat-creations** [comment]
Yes, you are right, maybe this would confuse others that are following the Field descriptions. However it would be nice to have some kind of validation-options on the text field. :-)

**Comment by laoneo** [comment]
There is an issue open for it with the number #119.
