### ISSUE TITLE
Unable to install the joomla with custom field package

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#132]
#### Steps to reproduce the issue
1. I downloaded the file https://github.com/joomla-projects/custom-fields/archive/custom-fields.zip
2. Then running the installation process
#### Expected result

Joomla is installed so I can test the custom fields feature
#### Actual result

The installation process stuck in the 3rd steps, see the image below : 

![screenshot](http://i.imgur.com/wyt8Ct0.gif)
#### System information (as much as possible)

Php 5.6.17
MySql 5.6.25

**Comment by hugofmsilva** [comment]
Try to edit your php.ini file and change max_execution_time to at least 90 seconds (max_execution_time=90).

**Comment by webchun** [comment]
@hugofmsilva thanks for the suggestion but it's still not working

**Comment by laoneo** [comment]
I fixed it, either you are trying to update your git installation, or download it again. Thanks for the report.

**Comment by webchun** [comment]
Nice, it's now working good ;)
