### ISSUE TITLE
Bug: Fields assigned to a Fieldgroup creating a new Fieldgroup with the name of the id

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#133]
Ok... it´s a weird bug but i try to explain:
#### Steps to reproduce the issue

1) I used the custom-fields contact PR
2) Created a new Field Group inside users "Authordetails" - this group received the ID 9 after creation
3) Created a new Field called "Authordescription" type textare and assiged it to Authordetails
4) A new Fieldgroup is created with the Name "9" and id 10
5) Went back to the field the Frieldgroup 9 was assiged, selected Authordetails again
6) A new Fieldgroup with the Name "9" and id 2 was created 
#### Expected result

The field should be assigned to the selected Field-Group
#### Actual result

The assignment creates a new group
#### System information (as much as possible)

Used the custom-fields contact PR 
Doesn´t happen in the main project

**Comment by laoneo** [comment]
Can you please link to the PR?

**Comment by coolcat-creations** [comment]
https://github.com/joomla-projects/custom-fields/pull/115

**Comment by laoneo** [comment]
Can you please retest it as I have merged all the fixes from the main branch to this one. If it still exists, I need to have a look, but I didn't change anything on that part of the code, which can influence this behavior.

**Comment by coolcat-creations** [comment]
Doesn´t happen anymore 👍
