### ISSUE TITLE
Enabling non-images files in the Media modal

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#136]
#### Steps to reproduce the issue
- I'm trying to attach a pdf file in an article, so user can download it
- So, I created a 'media' field
- Then when I added a new article I uploaded a pdf file via the 'media' field I created before
#### Expected result
- The pdf file is succesfully uploaded and listed in the modal so I can choose it to embed the link in my article
#### Actual result
- The pdf file is succesfully uploaded but not listed/showed in the modal

![screenshot](http://i.imgur.com/ZumRXLw.gif?1)

**Comment by laoneo** [comment]
Please open an issue on the [CMS repo](https://github.com/joomla/joomla-cms) as it is related to the media form field which is missing this configuration option. Please link the issue with this one then. Thanks for your help.

**Comment by webchun** [comment]
Done, thanks!
