### ISSUE TITLE
Field Group Access Level Bug

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#137]
#### Steps to reproduce the issue
1. I have a field group ABC with fields x,y,z inside it
2. I set Access level for field group ABC to Registered
#### Expected result

Field x,y,z will be visible in the frontend / article page when user logged in only.
#### Actual result

Field x,y,z are visible for public, no need to login to see them.

**Comment by laoneo** [comment]
Who should win the group and the field do have different access levels?

**Comment by webchun** [comment]
I think group should win, If user want to have a more complex access level rules they should they should leave group access to be Public and set each field items rules manually.

**Comment by laoneo** [comment]
But this would mean that the field wins?

**Comment by coolcat-creations** [comment]
No i also think the group should win...

**Comment by mbabker** [comment]
It should be the same as the inheritance for component -> category -> article as an example.

**Comment by coolcat-creations** [comment]
So Group is like a category...

**Comment by laoneo** [comment]
> It should be the same as the inheritance for component -> category -> article as an example.

This would mean the field does win.

> So Group is like a category...

Technically, yes.

**Comment by coolcat-creations** [comment]
No the group wins? :-) (confused)

**Comment by mbabker** [comment]
Considering view access levels have their own behavior compared to the "proper" ACL system, who knows what's winning anymore.

**Comment by webchun** [comment]
> But this would mean that the field wins?

Yes you right 😅
Anyway, I agree with @mbabker post

> It should be the same as the inheritance for component -> category -> article as an example.
> Considering view access levels have their own behavior compared to the "proper" ACL system, who knows what's winning anymore.

**Comment by laoneo** [comment]
I'v opened a PR #153 which should solve this issue. I'm closing this one. Please test the PR and leave feedback there. Thanks for the help so far.
