### ISSUE TITLE
Bug? Field options not applying

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#138]
I filled out the field options as following but see no effect in back or frontend:

Options:
![bildschirmfoto 2016-06-19 um 20 30 22](https://cloud.githubusercontent.com/assets/828371/16179112/ed259aaa-365c-11e6-8457-5ffb85137d19.png)

Also with an image icon
![bildschirmfoto 2016-06-19 um 20 30 35](https://cloud.githubusercontent.com/assets/828371/16179113/f0da9600-365c-11e6-854e-0ebae3bcb5c1.png)

Backend
![bildschirmfoto 2016-06-19 um 20 31 21](https://cloud.githubusercontent.com/assets/828371/16179115/f85b1fb2-365c-11e6-9471-0808ccffa105.png)

Frontend:
![bildschirmfoto 2016-06-19 um 20 31 31](https://cloud.githubusercontent.com/assets/828371/16179116/fb95a4a4-365c-11e6-9082-952100de6278.png)

**Comment by laoneo** [comment]
Can you please test the PR #143 and add your opinion what to do with the image options as they are not used till now. I'm closing this one as we have a PR for it. If there are some more options missing add them with a comment in the PR (probably I have to rename the title of the PR then).
