### ISSUE TITLE
Field Group Description doesn´t appear

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#139]
![bildschirmfoto 2016-06-19 um 20 55 11](https://cloud.githubusercontent.com/assets/828371/16179251/38c24a3c-3660-11e6-89ab-2e53c3841ce8.png)

Where does this text appear? is it even needed?
Maybe as an introtext in the Tabpanel?
Thanks

**Comment by laoneo** [comment]
It is used, when the fields are displayed in the tab.
![image](https://cloud.githubusercontent.com/assets/251072/16188880/085863ae-36d8-11e6-8266-a923562558de.png)

![image](https://cloud.githubusercontent.com/assets/251072/16188831/c9858f6c-36d7-11e6-88ad-d5c79d6b6416.png)

**Comment by coolcat-creations** [comment]
Ok... so there is a bug:
1) For com_user it doesn´t work

![bildschirmfoto 2016-06-20 um 17 28 20](https://cloud.githubusercontent.com/assets/828371/16200176/7c4f61d4-370c-11e6-89fa-304287d69be7.png)

2) In com_content the html tags are displayed:
![bildschirmfoto 2016-06-20 um 17 28 36](https://cloud.githubusercontent.com/assets/828371/16200183/81bde4e2-370c-11e6-9303-a27912f2856c.png)

3) Doesn´t appear in frontend also

**Comment by laoneo** [comment]
1. Is a "bug" in Joomla itself. I'v opened a PR https://github.com/joomla/joomla-cms/pull/10887. Can you please test it, that it can be merged.
2. Is fixed with commit 92f95e7b2ccfcf0c1d0963e7c80df04f39d728db.
3. Is fixed with the following commit.
