### ISSUE TITLE
Feature Request: Upload Field

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#140]
It would be very useful to have a secured upload field where an user can upload for example their Avatar or Logo or a pdf without seeing / having access to another files like it´s done in the mediafield.

**Comment by mbabker** [comment]
Wouldn't that just be the core "file" field type?  Dunno if that's
supported here or not.

The issue with that though is you have to have PHP code to handle the
upload.  The media field has this by way of com_media's controllers.  This
one isn't as easily configured solely at a UI level, or even if you have
direct access to a form's XML schema.

**Comment by coolcat-creations** [comment]
No It´s not available in the custom-fields till now...
Would be nice if there is a way to implement it for use-cases like this.

**Comment by laoneo** [comment]
I'm not sure as well, but I think this is part of the new media manager. @dgt41 is it?

**Comment by laoneo** [comment]
I would say use the media field for it. If you want to have it in a kind of "per user directory mode", then it would be the easiest way to add an additional option for it the media field. This means then that the directory would point to the user specific dir when somebody opens the article or whatever. But the only way I see it where it makes sense is is when a user edits his own profile. This option would confuse then different users when they edit an article or other global accessible items.

**Comment by coolcat-creations** [comment]
Or his own Articles ...

**Comment by coolcat-creations** [comment]
And the directory would need to create itself like images/contenttype/userid or something like this

**Comment by laoneo** [comment]
I'm closing this as an upload field already exists and it is part of the component to handle the upload. General upload functionality should be handled by the media manager. There is an [issue](https://github.com/joomla/joomla-cms/issues/10871) open which should allow to display more than only images in the media form field. The functionality to have a per home user directory is handled in issue #158.
