### ISSUE TITLE
Bug? Fieldvalidation Frontend uses wrong language

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#142]
I set the frontend to english but when i click on submit the validation is shown in german?

![bildschirmfoto 2016-06-19 um 22 49 19](https://cloud.githubusercontent.com/assets/828371/16179770/39bf1680-3670-11e6-8eab-f1b1e2a8b8b3.png)

**Comment by coolcat-creations** [comment]
For the email Field there is no message at all...

**Comment by mbabker** [comment]
That looks like browser validation, not Joomla.

**Comment by coolcat-creations** [comment]
Yes indeed, just checked in Firefox and there is another message. But how does this work? :-)
![bildschirmfoto 2016-06-19 um 23 03 23](https://cloud.githubusercontent.com/assets/828371/16179824/22fa74c4-3672-11e6-8bb6-16b69c965864.png)

And the Telephone field validation behaves also different (just clearing up the wrong characters) instead of an alert.

**Comment by mbabker** [comment]
I don't know enough about how browsers behave with HTML5 validation and input types so you'll have to consult the documentation on that.  I just know that the first screenshot is definitely a Chrome validation tooltip, not a Joomla tooltip.

On the telephone thing, again it might be based on the environment.  If it's using `<input type=tel">` there may be something stripping non-numeric characters.  I don't think that's part of the native HTML spec for browsers to do that so it may be something in Joomla's JavaScript libraries.

**Comment by coolcat-creations** [comment]
Ok thanks!

**Comment by laoneo** [comment]
Issue #119 already addresses to implement Joomla core validation.
