### ISSUE TITLE
Disabled and Read Only option

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#145]
#### Steps to reproduce the issue

I'm playing with the custom field's options, by switching Off / On field options : Disabled and Read Only for a text field
#### Expected result

If Disabled == On , a disabled input field will be displayed in the edit page, and if Read Only == On, a read only will be displayed
#### Actual result

There's no difference between. Enabling both of Disabled and Read option will show a disabled input text field. 

![readonlyt](http://i.imgur.com/JqQQtnb.jpg?1)

**Comment by coolcat-creations** [comment]
If you check the sourcecode there is a difference in the sourcecode. There might be Fields that are readonly but "active", disabled is "inactive"
For me it works. But i ask myself when we really would need "disabled" - in joomla logic we would just unpublish it.

**Comment by laoneo** [comment]
If you check the HTML code, then they have different attributes. Disabled or readonly. We had a longer discussion in issue #92. I'm closing this issue as it is working as expected.

**Comment by webchun** [comment]
okay
