### ISSUE TITLE
Image Option

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#146]
#### Steps to reproduce the issue

I'm creating a new custom field
In the Options tab, I choose an image 

![image](http://i.imgur.com/NLqmLPC.jpg?1)
#### Expected result

I'm expecting the image will be displayed in the article edit page or in the frontend
#### Actual result

The image is not displayed in the both of backend and frontend

**Comment by coolcat-creations** [comment]
That´s a duplicate of #138 which is in the PR #143 
Can you check this? thanks!!!

**Comment by webchun** [comment]
Ah ok. Sorry about that.

**Comment by coolcat-creations** [comment]
No need to be sorry - very happy you are here to test with us!

**Comment by webchun** [comment]
😉

**Comment by laoneo** [comment]
What should we do with the image? Please leave feedback on the PR #143.
