### ISSUE TITLE
Show On option issue

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#147]
#### Steps to reproduce the issue

I'm creating a new custom field and set the 'Show On' option to : Administrator
#### Expected result

The custom field will be displayed in the administrator page only
#### Actual result

The custom field  is displayed in both of administrator and frontend page

**Comment by laoneo** [comment]
The show on flag comes only into action when the form is displayed. To render it, it doesn't really makes sense to display it only on the back end, or?

**Comment by laoneo** [comment]
I guess this can be closed as the show on flag only defines on which form it is displayed, site or back end. This functionality works.
