### ISSUE TITLE
User field in the frontend editing

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#149]
#### Steps to reproduce the issue
1. I created a 'Create Article' menu item to allow user creating article from the frontend
2. I have 'user' type custom field
3. I logged in as super admin in the front end
4. I tried to create a new article
#### Expected result

When I clicked on user type custom field, it will return User list page
#### Actual result

When I clicked on user type custom field, it returned 404 page

![user](http://i.imgur.com/9F1TZDM.gif?1)

**Comment by laoneo** [comment]
The user field is not working on the front end. That's why you can't select a user as author for an article on the front as well. If you need this, then please open an issue against the CMS repo as it looks like it will be a bigger change. Or does such an issue already exists @brianteeman?

**Comment by brianteeman** [comment]
I cant find an example in the core where the user field exists in the frontend

**Comment by coolcat-creations** [comment]
Sorry if this is not directly issue related but i also ask myself when in general case the Timezonefield or Userdropdown or Usergroup custom-field would be used? Or do you have an example?
