### ISSUE TITLE
Placeholder for 'text' type

### ISSUE THREAD

**Issue by webchun** [joomla-projects/custom-fields#151]
#### Steps to reproduce the issue

Can we have placeholder in the 'text' type custom field? Because sometimes placeholder can be useful as a quick hint for text field, especially when you have multiple text fields (it's faster than hovering mouse over the input label to see field description)
#### Expected result

When creating a new text custom field there is a placeholder field in the General tab
#### Actual result

When creating a new text custom field there is no placeholder field in the General tab

![placeholder](http://i.imgur.com/HLJTzhN.jpg?1)

**Comment by laoneo** [comment]
In Joomla it is called hint. I'v added it as an option.

![image](https://cloud.githubusercontent.com/assets/251072/16222375/f49343a0-3797-11e6-953b-0c8645dbb913.png)
