### ISSUE TITLE
Field Type CAPTCHA not available on Content -> Articles (Field Tab)

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla-projects/custom-fields#16]
#### Steps to reproduce the issue

Log in on the back end.
Navigate to Content -> Articles.
Click on the left sidebar on Fields.
Click on the New button on the top.
Define a title and label **and select type CAPTCHA**
#### Expected result

Should display an CAPTCHA Field on Content -> Articles (Field Tab)
#### Actual result

Did not display an CAPTCHA Field on Content -> Articles (Field Tab)
#### System information (as much as possible)

Tested with latest installation of custom-fields.zip
Joomla! 3.5.0-rc4 Release Candidate [ Ember ] 16-March-2016 00:45 GMT 
Apache/2.4.18 (Win32) PHP/5.6.17 MySQL 5.7.10
#### Additional comments

I'm not sure what that type of field should effect. G recaptcha plugin is also enabled.
But as I can see every filed type did display as input on Content -> Articles (Field Tab)
See attached Screenshot, but CAPTCHA Field is missing there. 

Think captcha option field type should be removed from selection.
![captcha is missing](https://cloud.githubusercontent.com/assets/12803406/14203218/f9fce164-f7fc-11e5-9e07-df0855c4373c.jpg)

**Comment by brianteeman** [comment]
I had the same issue

**Comment by wilsonge** [comment]
Captcha can't render in the backend at the moment - that's a Joomla Core bug. But either way you don't want the captcha form rendering. What do you guys actually expect to happen?

**Comment by brianteeman** [comment]
Lets keep this open here until that is fixed

On 1 April 2016 at 22:18, George Wilson notifications@github.com wrote:

> Captcha can't render in the backend at the moment - that's a Joomla Core
> bug
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/16#issuecomment-204553440

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Thinking about it there really wont ever be a need for a captcha in the admin so all we need is a way to notify the end user that this type of field will not display in the admin and is only for the site? A tooltip would be a start but maybe something better than that?

**Comment by zero-24** [comment]
Why not add a message 'Here the captcha will be displayed in the frontend' or something similiar to the backend?

**Comment by wilsonge** [comment]
@roland-d started on it here https://github.com/joomla/joomla-cms/pull/8657

**Comment by laoneo** [comment]
This one got merged https://github.com/joomla/joomla-cms/pull/8657, so no errors anymore.
