### ISSUE TITLE
Fatal error: Access to undeclared static property: JFormFieldType::$blacklist

### ISSUE THREAD

**Issue by beni71** [joomla-projects/custom-fields#163]
#### Steps to reproduce the issue
1. Download the current code from github
2. Install it the joomla way (wizard)
3. After successful installation login to the administrator area
4. Open Menu Content > Fields
5. Klick "New"
#### Expected result

The Form to create a new field is opening.
#### Actual result

The following exception appears:
An error has occurred.
    0 Access to undeclared static property: JFormFieldType::$blacklist
#### System information (as much as possible)

From System > Control panel:
OS Windows
PHP 7.0.8
MySQLi 5.5.5-10.1.13-MariaDB
Time 18:56
Caching Disabled
Gzip Disabled
Users 1
Articles 68
Articles View Hits 81
#### Additional comments

The problem lies effectively in the file:

\administrator\components\com_fields\models\fields\type.php on Line 81:

if (in_array(strtolower($name), self::$blacklist))

The property "self::$blacklist" is not existing, but self::$BLACKLIST. It's an upper/lowercase problem!

**Comment by laoneo** [comment]
Thanks for the report. If you know the solution, can you please open a pull request :-)
