### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by hugofmsilva** [joomla-projects/custom-fields#164]
#### Steps to reproduce the issue

Click Content » Fields » New
#### Expected result

Layout to create new field
#### Actual result

Layout to create new field appears broken
#### System information (as much as possible)

Latest git version

**Comment by laoneo** [comment]
Can you provide a screenshot what is broken? Did you set error reporting to maximum in your joomla configuration? Is then an error shown?

**Comment by hugofmsilva** [comment]
Hello! Sorry, it's my fault. The layout is not broken.
