### ISSUE TITLE
Eradicate Harcoded DB Queries

### ISSUE THREAD

**Issue by wilsonge** [joomla-projects/custom-fields#170]
There's still a handful of harcoded custom field databases queries in here. These all need to use the main Database Query builder :)

**Comment by laoneo** [comment]
Where?

**Comment by laoneo** [comment]
Please add a comment on the pr https://github.com/joomla/joomla-cms/pull/11833 directly.

**Comment by zero-24** [comment]
I have add some inline comments with my CS PR did you saw them?
