### ISSUE TITLE
Missing quote mark in helper file

### ISSUE THREAD

**Issue by esedic** [joomla-projects/custom-fields#175]
### Steps to reproduce the issue

Just try to create a new field
### Expected result

There shouldn't be any PHP notices.
### Actual result

PHP notice "Use of undefined constant fullname - assumed 'fullname' in administrator\components\com_fields\helpers\internal.php on line 109" is visible.
### System information (as much as possible)

XAMPP on Windows 7
Apache 2.4.9
MySQL 5.5.36
PHP 5.4.27

**Comment by laoneo** [comment]
Please look on issue #171 for more information.
