### ISSUE TITLE
Can the title not be used as label

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#22]
What is the difference between the title of a field and the label? What is the use case for having both?

**Comment by laoneo** [comment]
The title identifies the field, the label is used to display it on the front. This was a requirement from one of my customers a couple of months ago. For most users it would be enough to have only one title, that's why I'v added a little javascript which fills the label based on the title.

**Comment by brianteeman** [comment]
It seems to be pretty useless to me and just adds complexity where it isnt needed - KISS

**Comment by laoneo** [comment]
I would leave it, users will have more flexibility, but perhaps move it down or to the options tab.

**Comment by brianteeman** [comment]
I dont see the need and if someone does need it cant they use the custom
output options

Right now the fact that you use js to copy a value from one place to
another shows it is a useless option for the majority

On 1 April 2016 at 17:16, Allon Moritz notifications@github.com wrote:

> I would leave it, users will have more flexibility, but perhaps move it
> down or to the options tab.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/22#issuecomment-204434800

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Just my 2 cents - I am also using `title` and `label` in my custom extension for fields. This helps to identify different fields with the same label.

**Comment by brianteeman** [comment]
Finally a usecase that i understand

**Comment by laoneo** [comment]
Then we leave it as it is.

**Comment by brianteeman** [comment]
can it be moved to the options tab as you suggested. Its just too confusing right now and will lead to a lot of questions

**Comment by b2z** [comment]
:+1:
