### ISSUE TITLE
CheckBox Options

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#26]
Are they really Options? A checkbox field is useless without them so maybe values is a better term?
It should also be a required field as without them it is useless
And because it is a required field I would put the select button higher up the field order - specifically above the Default Value field

**Comment by brianteeman** [comment]
Same comment for List field

**Comment by brianteeman** [comment]
Same comment for the Media field

**Comment by brianteeman** [comment]
Same comment for the Radio field

**Comment by brianteeman** [comment]
Same comment for the SQL field

**Comment by laoneo** [comment]
The default param can only be moved above the type specific fields like options or below them, not in between.

**Comment by brianteeman** [comment]
So you cant do this

![chhq](https://cloud.githubusercontent.com/assets/1296369/14211076/7176f87c-f82c-11e5-9d58-48c43fb60d6a.png)

**Comment by laoneo** [comment]
For the checkbox I can but for example on the gallery list, I can't put it between max width and recursive parameter. It can be before or after the for loop here https://github.com/joomla-projects/custom-fields/blob/custom-fields/administrator/components/com_fields/views/field/tmpl/edit.php#L62

**Comment by brianteeman** [comment]
Then its ok as on the gallery it would be the directory field that is both required and first see
![hgs4](https://cloud.githubusercontent.com/assets/1296369/14211332/b57c0fde-f82d-11e5-837c-3a63d85136f2.png)

**Comment by brianteeman** [comment]
Note I am not just saying that the position on the form is wrong but that they should be required

**Comment by laoneo** [comment]
Can you explain what should be marked as **required** for the media and sql field?

**Comment by brianteeman** [comment]
For the SQL field the query - 
For the media field the directory

**Comment by laoneo** [comment]
Guess you fixed it already with #55?

**Comment by brianteeman** [comment]
Looks like I forgot to set sql to be required

On 5 April 2016 at 07:48, Allon Moritz notifications@github.com wrote:

> Guess you fixed it already with #55
> https://github.com/joomla-projects/custom-fields/pull/55?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/26#issuecomment-205678510

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
It doesn't need to be required as it has already a default value.

**Comment by laoneo** [comment]
Can we close this or does it need some more actions?

**Comment by laoneo** [comment]
Guess this is done.
