### ISSUE TITLE
Editor Field, show button setting has no effect

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#27]
The show buttons option has no effect (probably since the code was changed to position them in tinymce toolbar itself) If not and there is a time for them to be displayed then please let me know as the tooltip is bad english and I can do a PR for that

**Comment by laoneo** [comment]
Is that something which has changed in Joomla 3.5? The [documentation](https://docs.joomla.org/Editor_form_field_type) states that the button option should control the buttons. If this is not accurate anymore then this checkbox can be removed.

**Comment by laoneo** [comment]
I'v tested it with the codemirror editor and with none editor and there it worked. Looks like it has to do with the new code mirror toolbar. To answer your question, yes please fix the language string.

**Comment by brianteeman** [comment]
Just making a note here to remind myself to work on this

**Comment by brianteeman** [comment]
No this is only to do with the tinymce editor. In Joomla 3.5 we changed the code so that the editor-xtd buttons were now present in the toolbar instead of at the bottom of the wysiwyg area see (https://github.com/joomla/joomla-cms/pull/7170)

As a result the Show Buttons and Hide Buttons options in the editor custom field have no effect when tinymce is the default editor

Also the settings for the height and width of the editor have no effect when tinymce is the selected editor - this is a known issue and not directly related to custom-fields but will cause support issues

**Comment by brianteeman** [comment]
Why did you close this?

**Comment by laoneo** [comment]
Because it is a "bug" in tynimce and should be addressed in the CMS repo.

**Comment by brianteeman** [comment]
NO it is not a bug in tinymce - tinymce is working perfectly as designed.
YOUR code is working as tinymce used to work before it was updated with the
Pull Request I referenced

AND even if you think thats the case please dont just close things without
opening the corresponding bug. Closing bugs like this without comment just
because .... makes anyone who contributes think why bother. It has made me
think

On 31 May 2016 at 08:03, Allon Moritz notifications@github.com wrote:

> Because it is a "bug" in tynimce and should be addressed in the CMS repo.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/27#issuecomment-222608003,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8ZMl_D9N04wfrkDyvlP3ZwOR2toHks5qG91JgaJpZM4H9sCY
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
> this is a known issue and not directly related to custom-fields but will cause support issues

From that phrase I though an issue exists and there is a bug in tinymce.

The code works in com_fields as it is documented https://docs.joomla.org/Editor_form_field_type.

**Comment by brianteeman** [comment]
I don't care what the documentation says. It doesn't work in reality.

**Comment by laoneo** [comment]
So how should we proceed then?

**Comment by laoneo** [comment]
@dgt41 can you help here as we got stuck.

**Comment by dgrammatiko** [comment]
@laoneo @brianteeman the code that moves the buttons inside tinyMCE's toolbar didn't touch the parent classes responsible for the bidding/showing of the buttons. So the question is: is this something that happens in tinyMCE or it happens in other editors (which one)?

**Comment by laoneo** [comment]
It happens only with tinyMCE in custom fields. When I set the hidden attribute to true in the article editor, then it works, but not on custom fields even tough the same XML tag is generated. If oyu need the steps to reproduce and debug the issue, let me know.

**Comment by dgrammatiko** [comment]
@laoneo I guess the misbehaviour comes form the dynamically created field. The steps will be helpful to try to debug this

I have a feeling that the custom fields are processed after the editor initialisation, thus not behaving as they should.

**Comment by laoneo** [comment]
- Download and install Joomla from this repo.
- Create an editor field on _Content -> Fields_
- Set hide button to true
- Save the field
- Open an article

The buttons are shown. To debug the generated XML, add a `echo $xml->saveXML();die;` to the file administrator/components/com_fields/helpers/fields.php after line 403. Then you will see the fulle XML string which is loaded into the form.

**Comment by brianteeman** [comment]
Here are some screenshots
Note that it is not possible to save an editor field without those two fields (readmore and pagebreak being marked as excluded)

As you can see when using tinymce it ignores the settings for editor buttons

![guam](https://cloud.githubusercontent.com/assets/1296369/16193084/04ca80de-36e5-11e6-98cf-f74bff61236d.png)
![rwjb](https://cloud.githubusercontent.com/assets/1296369/16193085/062e3038-36e5-11e6-9272-1c32e1956873.png)
![vxzf 1](https://cloud.githubusercontent.com/assets/1296369/16193088/0793a408-36e5-11e6-9139-934468cfc972.png)
![1tvt](https://cloud.githubusercontent.com/assets/1296369/16193090/0c13b914-36e5-11e6-8181-c2f685fc9e2f.png)
![fnde](https://cloud.githubusercontent.com/assets/1296369/16193093/0f838872-36e5-11e6-8724-cced4cfb5a6e.png)

**Comment by dgrammatiko** [comment]
@brianteeman I think this was fixed with https://github.com/joomla/joomla-cms/pull/9707. There must be something else committed after that that broke it again...

**Comment by laoneo** [comment]
Perhaps it is not yet merged into the 3.6.x branch, which is the base of custom fields.

**Comment by brianteeman** [comment]
Will manually apply that to this branch to check

**Comment by brianteeman** [comment]
I can confirm that with https://github.com/joomla/joomla-cms/pull/9707
applied to this branch then the problem is resolved

On 20 June 2016 at 13:33, Brian Teeman brian@teeman.net wrote:

> Will manually apply that to this branch to check

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
@brianteeman thanks for the test.

@wilsonge Can you please merge staging into the 3.6 branch. That I can update custom fields. Thanks.

**Comment by laoneo** [comment]
Staging is merged into custom fields. Can you please test if it is working now as expected that we can close this issue? Thanks.

**Comment by brianteeman** [comment]
Yes all looks good to me now.
