### ISSUE TITLE
Language string KEYS

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#3]
Is there a areason for this naming
COM_FIELDS_FIELD_FIELD_TYPE_LABEL

Should it not be
COM_FIELDS_FIELD_TYPE_LABEL

**Comment by laoneo** [comment]
That's a naming pattern I use in my extensions when you have multiple items like event, location, etc.

COM_FIELDS_FIELD_FIELD_TYPE_LABEL means the item field and the field of it. But in the case of com_fields it doesn't really makes sense.

**Comment by brianteeman** [comment]
Thanks
