### ISSUE TITLE
Automatic Display - inherited

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#31]
What does inherited do? Where is it inherited from?

**Comment by laoneo** [comment]
Are you talking about the setting where to display it? It inherits from the system plugin.

**Comment by brianteeman** [comment]
Yes the setting called "Automatic Display" 

If it is set in the plugin then I would call that "Default"

**Comment by brianteeman** [comment]
Inherited is more often used in something like K2 where an option is inherited from another item higher up the tree. In this case you are making a Default setting in the plugin

**Comment by brianteeman** [comment]
Actually thinking about it we normally call this a "Global" not a default

**Comment by brianteeman** [comment]
Solved with 579ddf81929538071b81396e06bc8a2ba49157b1
