### ISSUE TITLE
Toolbar Buttons

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#35]
Fields has an Options button but it is options for articles
Fields has no Help button

Field Categories has an Options button  but it is options for articles
Fields Categories has a Help button but it is for 
https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help35:JHELP_COMPONENTS_CONTENT_ARTICLE_CATEGORIES

**Comment by laoneo** [comment]
Options should point to articles and help is in progress by @chrisdavenport.
