### ISSUE TITLE
New core rule edit.value

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#46]
Should the file dprules.php be renamed rules.php
and the class JFormFieldDPRules JFormFieldRules

or something like that?
https://github.com/joomla-projects/custom-fields/blob/custom-fields/administrator/components/com_fields/models/fields/dprules.php

**Comment by wilsonge** [comment]
The doc block states it's adding in a non-core level so presumably it needs to be made a new core level in our components then this field is just removed in its entirety?

**Comment by laoneo** [comment]
@wilsonge exactly. If it is ok to introduce a new core rule _edit.value_, then this can be removed. Otherwise the edit permissions needs to be set for every field explicitly as no inheritance comes into action.

Probably a decision needed to be done by the PLT.

**Comment by wilsonge** [comment]
Is this on a component by component basis?

**Comment by laoneo** [comment]
If I understand you right, then yes it is per component which integrates com_fields. A field can inherit it from a category or the component itself, when it is not assigned to a category.

**Comment by wilsonge** [comment]
Then go merge it in :)

**Comment by laoneo** [comment]
You mean adding a new rule to the core? Will make a pr for that.

**Comment by wilsonge** [comment]
Yes I do :) looking forward to the PR!

**Comment by wilsonge** [comment]
Closing this in favour of the PR #75
