### ISSUE TITLE
Multilanguage not working

### ISSUE THREAD

**Issue by Flowman** [joomla-projects/custom-fields#47]
#### Steps to reproduce the issue

Create a site with multiple languages

Create two fields for each language.
![field](https://cloud.githubusercontent.com/assets/212680/14226127/93b3066c-f90b-11e5-95b8-9c3d0518e701.PNG)

Create two articles for each language.
![articles](https://cloud.githubusercontent.com/assets/212680/14226130/a5412a4e-f90b-11e5-83c1-807d357be6da.PNG)

Edit article with same language as backend, field will be the same as backend.
![article-en](https://cloud.githubusercontent.com/assets/212680/14226136/b91c1402-f90b-11e5-826e-d5118fc914e9.PNG)

Edit the article with the language that is different from backend, field will still default to the langugage of the backend,
![article-sv](https://cloud.githubusercontent.com/assets/212680/14226146/e61e22b0-f90b-11e5-91c2-612d0e2101e7.PNG)

This is all okay but when we save it will save the field for the backend language and not show up on the frontend.
![front-art](https://cloud.githubusercontent.com/assets/212680/14226154/1bcc5dbe-f90c-11e5-8aaf-25f5948a7b1a.PNG)

Change backend language to the same as the article edited, and the field will show up fine in the frontend.
![front-ar](https://cloud.githubusercontent.com/assets/212680/14226157/2d3927da-f90c-11e5-872f-25c66710fc6c.PNG)
#### Additional comments

This can be fixed if we create fields associations, and on save it checks for the associated field and save the value. Same for loading the fields, check if associations exists and load the value.

**Comment by Flowman** [comment]
So we mixing the languages for the backend? My backend is English but will show the field label for the article language in this case swedish. Must be a better way to fix this.

Got a new error after that fix. Notice: Array to string conversion in C:\WAMP\www\custom-fields\administrator\components\com_fields\models\fields.php on line 108

**Comment by laoneo** [comment]
There is no way around it. That's how Joomla's multilanguage feature works. You are also no expecting an article in Swedish that it will appear in English on your back end. What you are expecting goes more into the direction of Fobla.
