### ISSUE TITLE
Fields reference in render

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#48]
https://github.com/joomla-projects/custom-fields/blob/custom-fields/components/com_fields/layouts/field/render.php#L28

We probably should be changing this

**Comment by dwrianto** [comment]
Playing w/ table, looks nicer for me. Yet, need to do more tests with another types.

![img-j3-customfields](https://cloud.githubusercontent.com/assets/875973/14232094/bd8cd5e2-f9c6-11e5-8c8b-b36f70234163.png)

**Comment by wilsonge** [comment]
The idea of that rendering (I think) is to blend it in with the existing article information at the top  (in the details section)

**Comment by laoneo** [comment]
Yes, but it is possible for every component to override it. Here it is loaded https://github.com/joomla-projects/custom-fields/blob/custom-fields/plugins/system/fields/fields.php#L343 and here checked if the component can render it https://github.com/joomla-projects/custom-fields/blob/custom-fields/administrator/components/com_fields/helpers/fields.php#L209. For example in DPCalendar the output of the fields do look different than for articles.
