### ISSUE TITLE
Mixed language strings

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#5]
It is confusing to me to see this

>   < field name="description" type="editor" label="JGLOBAL_DESCRIPTION"
>         description="COM_FIELDS_FIELD_FIELD_DESCRIPTION_DESC" filter="JComponentHelper::filterText"
>         buttons="true" hide="readmore,pagebreak" height="10" />

Where some strings come from existing files and other strings come from this component. I am sure it will be better (especially for the translators) if we are consistent and in this case only use strings from the component.

Or is there a reason that I am missing?

**Comment by laoneo** [comment]
I was lazy on DPFields to create strings which are available, bit with com_fields I totally agree that we should use strings only from the component.

**Comment by b2z** [comment]
> I was lazy on DPFields to create strings which are available

I do the same for my components :smile: But yes, this should be consistent in the core of course.

**Comment by laoneo** [comment]
Hope somebody can help out here.

**Comment by brianteeman** [comment]
I am working on this today - at least a first draft PR anyway

**Comment by brianteeman** [comment]
I took a long look through the strings and it appears that the only strings that are re-used are global strings and we have a habit of reusing those anyway so for now there is no change needed.
