### ISSUE TITLE
Merge DP Field Rendering with Joomla Form Fields

### ISSUE THREAD

**Issue by wilsonge** [joomla-projects/custom-fields#51]
Carried forward from initial Joomla PR

Basically we need to integrate the fields @ https://github.com/joomla-projects/custom-fields/tree/custom-fields/components/com_fields/layouts/field/prepare with the fields built into Joomla (https://github.com/joomla-projects/custom-fields/tree/custom-fields/libraries/joomla/form/fields)

**Comment by brianteeman** [comment]
Agree - there is quite a few areas of duplication right now

**Comment by laoneo** [comment]
What you are referencing are layouts. I don't see any way of merging them into to the default form fields. What makes more sense is to merge the types (https://github.com/joomla-projects/custom-fields/tree/custom-fields/administrator/components/com_fields/models/types) which do create the XML for the form to merge them into the default form fields.

**Comment by laoneo** [comment]
Closing this one as we have a PR for it. @wilsonge can you please leave some feedback on the PR.
