### ISSUE TITLE
Integration with Joomla search

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/custom-fields#57]
At the moment com_fields is very much isolated. Would be nice to have it integrated into Joomla search. 

To implement it, the com_content search plugin needs to expand the search query to com_fields. Question here is if it should go directly to the database tables or should the com_field helper offer some sort of JQuery (not jQuery) manipulation? In DPCalendar I'v solved it, by going directly to the db tables.

Or can it be solved with a complete new plg_search_fields plugin?

Another challenge is that the fields value table only stores references for some field types. For example the list field stores only the keys and not the values. If the key doesn't contain the value string (which mostly doesn't), the field will never be found.

**Comment by brianteeman** [comment]
Whatever is done remember it has to be for both search and finder (aka smart search)

**Comment by brianteeman** [comment]
I see that there is already some code for finder in the system plugin

**Comment by laoneo** [comment]
Yes finder is already done. Only the default search needs to be implemented.

**Comment by Bakual** [comment]
Imho, an own plugin gets to complicated since you need to know in the com_fields search plugin what the URL is for the item (article, whatever) where the field is living in.
I would just adjust the search plugin for each extension to also (optionally?) search the custom fields. Searching directly in the database is likely the simplest and fastest approach.

**Comment by mbabker** [comment]
You'd have to do it on a search plugin (for both search components) basis.  The search components themselves are largely unaware of the data structures of components implementing support for them.  Plus they're designed to be routed to content items, I don't think fields are something you'd assign a URL to and route pages to.  So Thomas is right here, the plugins need to be adjusted in a way that would allow more fields to be optionally searched.

**Comment by brianteeman** [comment]
Could there be a param for each field to indicate if it should be included
in searches or not. I;ve seen several other extensions work this way

On 6 April 2016 at 21:04, Michael Babker notifications@github.com wrote:

> You'd have to do it on a search plugin (for both search components) basis.
> The search components themselves are largely unaware of the data structures
> of components implementing support for them. Plus they're designed to be
> routed to content items, I don't think fields are something you'd assign a
> URL to and route pages to. So Thomas is right here, the plugins need to be
> adjusted in a way that would allow more fields to be optionally searched.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/57#issuecomment-206534907

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
There could, the plugins would need to be smart enough to read that data and convert it to the structure needed.

**Comment by laoneo** [comment]
@nibra brought me to the path, that we face here the same problem as com_tags has. They solved it trough a helper https://github.com/joomla-projects/custom-fields/blob/custom-fields/components/com_tags/helpers/route.php#L35. Reusing that would solve the issue, or?

**Comment by Bakual** [comment]
Personally, I didn't like much the approach from com_tags. But that's me.
Are you storing the content types in your field tables? Because you will need those to figure out which routerhelper method to call.
I think it would be much simpler to just adjust the search plugin of the components.

**Comment by laoneo** [comment]
Personally it's also my favorite to adapt every component. What is stored in the fields table is the context the field belongs to, eg. com_content.article. Like that the routing similar to com_tags can be done.

**Comment by Bakual** [comment]
> What is stored in the fields table is the context the field belongs to, eg. com_content.article. Like that the routing similar to com_tags can be done.

Yep, then it could be done similar. I still don't think it should be handled by com_fields but it would be possible.

**Comment by wilsonge** [comment]
Every component has some sort of routing helper these days (definitely in core anyhow). If we can extend the existing libraries routing helper it seems like relatively common sense to avoid code duplication to me....

**Comment by nibra** [comment]
Adjusting the components' search plugins would prevent com_fields to work wiith extensions search-wise, so it's not really an option. Although the com_tags approach seems ugly, it is the best fit for this problem. As a next step, this and com_tags' routing can be refactored into JRouteHelper.

**Comment by brianteeman** [comment]
> Adjusting the components' search plugins would prevent com_fields to work wiith extensions search-wise, so it's not really an option. 

How?

**Comment by wilsonge** [comment]
Well components already need to make modifications to integrate with com_fields (the extra permissions level etc). So honestly I don't have a problem with components needing to modify their own search plugins to integrate.

**Comment by mbabker** [comment]
What's the actual goal for the search integration?  If it's to make the data of an extension's custom fields searchable, then IMO it needs to be plugged into each extension's search plugin(s).  If com_fields has a routable front end that displays data, then com_fields needs to provide search plugin(s) as the other content based components do.  I'm not sure how doing this work in the search plugins prevents things from working correctly.

**Comment by nibra** [comment]
@brianteeman Each external search plugin would have to be modified, giving the tight coupling, we urgently need to get rid of. That's not the case, if the external components' router is utilised instead. Thus the latter is preferable, even though it's not perfect.

**Comment by brianteeman** [comment]
Why does it matter if its the router or  the plugin that is updated

On 7 April 2016 at 12:55, Niels Braczek notifications@github.com wrote:

> @brianteeman https://github.com/brianteeman Each external search plugin
> would have to be modified, giving the tight coupling, we urgently need to
> get rid of. That's not the case, if the external components' router is
> utilised instead. Thus the latter is preferable, even though it's not
> perfect.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/57#issuecomment-206832860

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
How does the router tie in to search though?  The search plugins are how the data to be searched is defined.

**Comment by Bakual** [comment]
If you use the routehelper, then com_fields would return own results for the custom fields additional to the one from the extension search plugin. This may generate duplicate results (one from the extension plugin and one from the fields plugin). It also may generate other ugly issues.
For tags it was a different premise as com_tags has own frontend views. Imho, com_tags doesn't need the routehelper for the search (search results go to com_tags views), it needs it to generate the extension links in the com_tags views, to build proper URLs for the tagged extension items. So it's a different use case.

**Comment by nibra** [comment]
@brianteeman The router does not need to be updated - it just builds the link to the item in the search result.
@mbabker The returned search result contains a link to the item. That link has to be created.
@Bakual That's a general problem of the search component. It should consolidate the results from all search plugins.

**Comment by wilsonge** [comment]
If I add new fields to a article the link to the article doesn't change from what it is now? All we need to do is add the new fields to the search criteria as i understand?

**Comment by mbabker** [comment]
> If I add new fields to a article the link to the article doesn't change from what it is now? All we need to do is add the new fields to the search criteria as i understand?

That's exactly what I'm thinking.  So what's different with fields that it can't use this logic?

**Comment by Bakual** [comment]
> @Bakual That's a general problem of the search component. It should consolidate the results from all search plugins.

@nibra No, it's not a problem at all since currently there can't be any duplicates. Each extensions has its own plugin with its own search result set. There is nothing to consolidate.

**Comment by laoneo** [comment]
> If I add new fields to a article the link to the article doesn't change from what it is now? All we need to do is add the new fields to the search criteria as i understand?

In DPCalendar I did it that way with DPFields:

`$query->join('LEFT', '#__dpfields_fields_values AS dpf ON dpf.item_id = a.id and dpf.context = ' . $db->q('com_dpcalendar.event'));`

Honestly I don't like that an extension needs to reference a table which doesn't belong to it. But it is widely used that extensions do join joomla core tables.

**Comment by Bakual** [comment]
> Honestly I don't like that an extension needs to reference a table which doesn't belong to it.

It's needed for several reasons in many places. We need to join user tables, categories tables, language association tables. There is nothing wrong with that by itself.
I'm happy if there is a method to fetch the custom fields in an extension view so we don't have to add the joins to each model. But for the search plugin I think it's just the simplest approach to directly join the fields table. The way the plugins work I don't think you can have a simple helper method to help here.

**Comment by chrisdavenport** [comment]
I'm not understanding why we would need to do any table joins here (at least for Smart Search; I'm not sure about the old search).

Yes, we need to keep extensions, search and custom fields decoupled from one another.  This can all be done using events and plugins.  Almost everything required is already in place.

The extension-specific search plugin, such as PlgFinderContent, handles the pre-defined extension fields (introtext, author, etc.).  In its index() method, just before handing the content item over to the indexer, it calls FinderIndexerHelper::getContentExtras($item); which fires an onPrepareFinderContent event.  I haven't checked, but this line of code should be in all core Smart Search plugins already.  It allows a plugin to add extra fields, taxonomies and processing instructions to the search object before indexing takes place ($item is an instance of FinderIndexerResult).

All you need to do is write a plugin for custom fields that will listen for the onPrepareFinderContent event, retrieve any custom fields for the $item it's been given, then update it with any indexable fields, taxonomies and instructions it finds.

When a custom field is defined, I think there needs to be some way of saying whether it is indexable (meaning that it will be parsed for search terms), mappable (meaning the value will be added to a specified taxonomy) and weightable (meaning that a weight is assigned to search terms in fields of that type (which will be added as a processing instruction)).  I'm sure you can come up with better terms than "indexable", "mappable" and "weightable", but I hope you understand what I mean.

Finder was specifically designed to handle this sort of thing.  No need to invent something new and no need for any table joins.  Routing is already handled by the search plugins so we don't have to solve that problem.  (You might need to do something hacky for the old/simple search though).

**Comment by Bakual** [comment]
@chrisdavenport It was about old search, not smart search (finder) :smile:

**Comment by laoneo** [comment]
Yes, the finder part is already done https://github.com/joomla-projects/custom-fields/blob/custom-fields/plugins/system/fields/fields.php#L484.

**Comment by chrisdavenport** [comment]
Ahh, okay.  That's why it didn't make sense. :-)

**Comment by laoneo** [comment]
If the search plugin of the component it belongs to will do the join, then the same join can be used in the model when a search filter is set.

**Comment by laoneo** [comment]
I guess there is no proper way to do it in a separate fields search plugin. Components which do integrate com_fields need to do the joins by them self like they do already for categories, access levels, users, ....

**Comment by wilsonge** [comment]
Agreed. Can you make sure that join is in place for the core components please?

**Comment by laoneo** [comment]
Hope somebody else con volunteer on that, as I'm now on #51.

**Comment by laoneo** [comment]
Asking for feedback on #83 as I did forget something for sure.
