### ISSUE TITLE
Move gallery javascript library to Joomla core

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/custom-fields#58]
Should the fotorama javascript library be moved to the Joomla core?

https://github.com/joomla-projects/custom-fields/tree/custom-fields/media/com_fields/js

**Comment by brianteeman** [comment]
when you say moved to the core what do you mean?
and we probably should include the non-minified version as well 
and should we include the licence notification

**Comment by laoneo** [comment]
Moving it to the common js folder https://github.com/joomla-projects/custom-fields/tree/custom-fields/media/media/js. Perhaps some other extensions will use it too in their code in the future.

**Comment by brianteeman** [comment]
I dont think its needed - other components like finder have their own
directories and any extension can access the folder as it is

On 5 April 2016 at 08:11, Allon Moritz notifications@github.com wrote:

> Moving it to the common js folder
> https://github.com/joomla-projects/custom-fields/tree/custom-fields/media/media/js.
> Perhaps some other extensions will use it too in their code in the future.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/58#issuecomment-205689908

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
Just wanted to clarify it.
