### ISSUE TITLE
Empty category

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#62]
It is possible to save a field without a category. I understand why but it is non-standard behaviour with the rest of joomla where you cant save an item without placing it in a category. eg contacts, newsfeeds, etc

To resolve this we would need to hve a default category for fields created at install time eg uncategorised

Note this would also solve #19

**Comment by laoneo** [comment]
That would mean for every component which is installed a category needs to be created, despite the fact it uses com_fields or not. On multilanguage sites a category for every language needs to be created too. Or how would you solve the initial setup? The only way I can think of is to create a category on the fly when the new field button is clicked, but that looks more like a hack.

**Comment by brianteeman** [comment]
1. Does that mean fields is going to support all components and not just
   content? If so then it really needs to move to the components menu
2. Why does a component that doesnt use com_fields need to use categories -
   I dont see the requirement

On 5 April 2016 at 11:54, Allon Moritz notifications@github.com wrote:

> That would mean for every component which is installed a category needs to
> be created, despite the fact it uses com_fields or not. Or how would you
> solve the initial setup? The only way I can think of is to create a
> category on the fly when the new field button is clicked.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/62#issuecomment-205754942

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
com_fields is intended to be integrated as com_categories and not as a standalone component. What I wanted to say is that the field categories are component specific. If you create a fields category in com_content, then it will not be shown in com_users.

**Comment by laoneo** [comment]
Closing, because there is no proper way to implement it.
