### ISSUE TITLE
A great addition to Joomla! but what about custom content types?

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla-projects/custom-fields#67]
#### Steps to reproduce the issue

HI

A great addition to Joomla! but what about custom content types? Did I miss something here but custom fields are above all useful to create one's own content types aside from traditional articles.

I understand here that these custom fields are a first stone for a possible future embedded cck.

thanks

cyril

**Comment by wilsonge** [comment]
We aren't looking to build a full CCK with this. We are looking to cover basic custom field usage. Custom content types are outside the scope of this entire project and we'd go at that via the tags route of core content tables - rather than this concept of dynamically adding fields via JForm
