### ISSUE TITLE
Move plugin methods to appropriate groups

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/custom-fields#71]
The system plugin looks to be pretty big, yet none(?) of its methods actually need to be in the system plugin group.  Most are for content events, some are for user events and one is for a finder event.

Bearing in mind that system plugins are loaded and parsed on every single page request, would it not be better to move these methods to separate plugins in more appropriate groups?

**Comment by laoneo** [comment]
Makes sense.

**Comment by wilsonge** [comment]
I think actually there's a balance to be had here. I personally have been of the opinion that grouping plugins together by functionality is required. If the user removes one plugin but keeps the other plugins enabled then things have the potential to break hard. Also we don't want to make it very hard for a user to disable this is they want to (say because they are using fabrik or whatever) - and having to disable 3/4+ different plugins could be problematic....

Don't get me wrong - from a technical perspective you are correct Chris - but I think we have to keep an end user perspective here as well.

**Comment by b2z** [comment]
If there is a tight coupling then I am also with @wilsonge - let's keep it in one place.

**Comment by chrisdavenport** [comment]
I would be surprised if disabling the user plugin would cause a problem with the content plugin.  Or vice versa.  If that sort of tight coupling exists, then we should look for the cause and see if it can be eliminated.  Dumping code into system plugins when it doesn't need to be there is a bit like using global variables in PHP code: we shouldn't do it.

As far as UI is concerned, I agree that it should be as simple as possible to manage the component, but I think that can be done with some additional checks and warnings.  Look at Smart Search for an example of how the component checks the state of a critical plugin and warns the user if it is not enabled.  Conversely, if the plugin depends on the component being enabled, then simply include a check in the plugin code so it doesn't "break hard".

**Comment by brianteeman** [comment]
I'm all for less plugins. Some extensions have 20-30 which makes management a real pain

**Comment by javigomez** [comment]
Not talking about core but 3rd party to add ideas. 

We had that situation and we use `package` to group the plugins. We also added a script to avoid user uninstalling individual plugins, and recommending to uninstall the package instead. And we also add a message in system-message-container of each plugin in case you are missing other required extension:

![screen shot 2016-04-15 at 09 51 18](https://cloud.githubusercontent.com/assets/1375475/14554835/a6038b32-02ef-11e6-90a4-93298a39552c.png)

**Comment by laoneo** [comment]
That looks for me as too much effort for a lightweight component as com_fields is by now.

**Comment by laoneo** [comment]
I guess we are leaving it as it is. The future will show if separation is needed or.
