### ISSUE TITLE
Create a menu entry for com_fields under Components

### ISSUE THREAD

**Issue by Flowman** [joomla-projects/custom-fields#73]
Can we add Fields to the Components menu. Why would we do this? 

When creating a fields it should ask for which component to add the fields too and we suddenly have field support for every single component. 3 party vendors does not need to implement the fields support into their components, or they could if they want the extra menu item to only show the fields for their component.

**Comment by laoneo** [comment]
This would not work as the component needs to fulfill some basic requirements as described here https://joomla.digital-peak.com/documentation/162-dpfields/2756-developer. Also to enable search within the component as we are discussing it in issue #57.

**Comment by Flowman** [comment]
Yes it only depends that the component has the right event triggers, and that means that every component that already has those triggers are compatible with the fields component.

So we could easily still have a default menu item for fields, and its nice with a full overview of all fields in one place.

I bring this up as a discussion as there is better ways to implement fields than that it is right now. @laoneo you mentioned in your blog post you wanted the community help to improve fields. So have an open dialog instead of closing stuff.

**Comment by laoneo** [comment]
How would you detect then if the component has the triggers? Believe me having a fields component menu item and the fields on every component would confuse people. You also don't have that for categories.

I closed this issue because com_fields is intended to be integrated into a component as it would belong to the component. Maybe I'm missing your use case. If you can tell us more why this would be a cool thing to have, then we need a bit more background information. I closed this, because it would break the whole concept of com_fields.

**Comment by brianteeman** [comment]
I agree that com_fields should be in the components menu and not the content menu. If it can be used with all components then it doesnt belong in the content menu

**Comment by laoneo** [comment]
The intention is to use it like com_categories which also doesn't have it's own menu item. When you have a look on the users manager, there you will also see new menu items Fields and Fields Category. Every component which want's to integrate com_fields needs to add them to their menu. com_fields is not intended to be a single component. com_ajax also doesn't have it's own component menu entry. It is meant to integrate it, but not to be used as a standalone extension.

**Comment by Flowman** [comment]
The concept in taken. But for some admin a place for global management is good to have. So they don't need to drill down to each component to find the fields.

Another use case is when you remove a component the field data is still in the db, so you can still remove fields even after the component is deleted.

How are field types from third party components handled? I got a quiz component I build and want to publish its model item selector to articles. This could be one more use case, add an extra menu item for field types so you can manage third party fields.

As I suggested this is not to replace the component sub menus but to add a global management point.

**Comment by laoneo** [comment]
When a component is removed, then the data from the database needs to be removed as well. Looks like you found a bug.

At the moment field types are handled within the component itself. Have a look on DPCalendar. It contains a types folder in the folder administrator/components/com_dpcalendar/models/. It is a calendar type which allows to associate as many calendars they want to an event.

I understand that it is not a replacement but it is against the idea of com_fields. You also don't have a menu for com_categories, com_history or com_ajax.

**Comment by Flowman** [comment]
Better example. I have my \components\com_quiz\models\fields\modal\quiz.php it is a quiz selector like the \components\com_content\models\fields\modal\article.php. I decide that i want to make my field available to every single component that has com_fields enabled.

If i want my field available in com_content or another component, how do i link it in? This is where we could use a table for field type where component developers can add there custom fields, and back to the global management of fields. I know you don't like it but think outside the box. It would be great if Joomla had a entry in the menu for global management of categories too.

**Comment by laoneo** [comment]
I would rather go with a plugin. Means we will introduce a new plugin category fields, where extension developers can introduce new field types. This is then not even bound to a component.

**Comment by laoneo** [comment]
Please open another issue, that when a component is remove from Joomla, that the fields will be deleted as well.

**Comment by laoneo** [comment]
Closing it as it doesn't fit into the concept of com_fields. Making it global will not work as not every component does support com_fields out of the box. If a component does it needs to actively enable it as com_content as com_users do. I suggest that we wait with the request. If there is a need for a global fields management view, then it needs to be done in a separate project at a later stage when com_fields is established.
