### ISSUE TITLE
Feature request: Assign each field to one/more categories and subs

### ISSUE THREAD

**Issue by skelgaard** [joomla-projects/custom-fields#77]
It would be really helpful to make a full diverged system, you should be able to assign the custom field to only be active for a selected list of categories and their sub categories (optional).

This way you can have articles, that do different types of items in them, where there is need for different fields and that will make custom fields even more usable.

Same goes for user fields based on members groups.

For both fields a both view/edit level would be nice to be able to set on each field, take a look how its made for the component "easy profile"  which have a good implementation for profiles, but still has a few things that could be made better.

**Comment by laoneo** [comment]
Would that mean you have the same field used for the same article more than once? This would be hard to implement, especially the permission inheritance would become difficult when the field belongs to more than one category. But would be interesting to see a PR for it. Sorry but I just don't have time to do it.

**Comment by skelgaard** [comment]
@laoneo i have been testing some more and seems some of thoose features in regards to fields for categories is implemented, but i have found a bug in them

I have created 2 categories (test and test2)
![3](https://cloud.githubusercontent.com/assets/13235820/14761995/d9a76a86-096f-11e6-9ff8-0f3479dcf068.JPG)

i have created the same 2 field categories with same names
![1](https://cloud.githubusercontent.com/assets/13235820/14761992/d96f31ac-096f-11e6-888f-73b10381db3d.JPG)

I have created 2 fields one for each field category/category set
![2](https://cloud.githubusercontent.com/assets/13235820/14762002/1f54de74-0970-11e6-85f4-5998047dd77a.JPG)

Now i go and create a new article, both test and test2 shows up
![4](https://cloud.githubusercontent.com/assets/13235820/14761994/d998ae4c-096f-11e6-987a-0afe23c14326.JPG)

I change to test category and only test shows up
![5](https://cloud.githubusercontent.com/assets/13235820/14761996/d9b9afa2-096f-11e6-94c3-fba8690bd974.JPG)

I now change back to uncategorised and none of them shows up, as expected on first article create
![6](https://cloud.githubusercontent.com/assets/13235820/14761997/d9bb12c0-096f-11e6-808d-84ced53f311e.JPG)

Now thats all good then, if none shows up, before category is selected when assigned.

There could be 2 good things more done, frontend and backend edit template for the category then.
If you look at component "content builder" it has the ability to create a template for editing these items and displaying them. This can also be done as K2 does it, where you can create own templates in templates/TEMPLATENAME/html/com_k2/template/YOURSTYLE/files...

In users i cannot assign a field only to a usergroup like i can with a field in articles to a category

This would be good if you had a site with both cars, motorcycles etc on it, and there could be made easier edit page for ppl to use depending on which category is selected.

I hope you get what i mean, else i will gladly try to explain it more to you even over a voice chat.

**Comment by skelgaard** [comment]
Also if you in some way would be able to create a menu item (i kind of copy of articles) that lead directly to my test2 category, it could be very much easier for none programmers to edit a site with 5 different types if items, just go under content, select the kind of items you want to edit, like cars and then it would be "filtered" to that category automatic with the edit layout on first screen that fits this type of items, instead of having to sit and switch around between different tabs and self filter.

Again it is a wish that could make Joomla so much more usable for folks that don't know that much in computers and websites, but still need to maintain their data on the page.

**Comment by laoneo** [comment]
Please open for every request/issue/bug a new issue. Discussing multiple things in one issue is too complicated to follow. I'm closing this one as it is solved according to your comment, or?
