### ISSUE TITLE
Should we introduce deprecated code with a new component?

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/custom-fields#8]
See: https://github.com/joomla-projects/custom-fields/blob/custom-fields/components/com_fields/layouts/fields/render.php#L73-L86

What does this mean and why should we introduce deprecated code by shipping a new component?

**Comment by wilsonge** [comment]
We shouldn't put in deprecated code :) It should be removed

**Comment by laoneo** [comment]
It's from the early days of DPFields.
