### ISSUE TITLE
Show List Option's Value instead of Key in frontend?

### ISSUE THREAD

**Issue by justinherrin** [joomla-projects/custom-fields#81]
I have a List Field added to the User's profile, and when viewing the user's profile in the frontend, it shows the key of the selected list option instead of the value.
#### Steps to reproduce the issue

Create a new field of List type, add a few key/values pairs to the drop-down list.
![list-key1](https://cloud.githubusercontent.com/assets/13225615/14807831/e7f094fc-0b4d-11e6-8fc3-ab02e1d5e5ba.png)
#### Expected result

To see the option's Value in the frontend.
#### Actual result

The option's Key is listed in frontend...
![list-key2](https://cloud.githubusercontent.com/assets/13225615/14807829/de0842aa-0b4d-11e6-8e70-687f2a1d3fee.png)

**Comment by laoneo** [comment]
Thanks for testing it on com_users!!
