### ISSUE TITLE
travis issue; travis cant find the repo?!

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/custom-fields#85]
#### Steps to reproduce the issue

See:
![wp_ss_20160511_0001](https://cloud.githubusercontent.com/assets/2596554/15171753/4eb202c0-1751-11e6-8e33-d3ee656860bc.png)
#### Expected result

Travis run
#### Actual result

Travis don't run

Can a maintainer have a look into that?

@wilsonge @laoneo @roland-d

**Comment by laoneo** [comment]
It does https://travis-ci.org/joomla-projects/custom-fields/builds, or do I miss something?

**Comment by zero-24** [comment]
https://travis-ci.org/joomla-projects/custom-fields/builds/129340119

See there ;)

**Comment by zero-24** [comment]
Lol now it works :( thanks for looking
