### ISSUE TITLE
Field Category bug

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#86]
With the current branch try to create a new category then you get an error
JFolder: :folder: Path is not a folder. Path: /htdocs/custom-fields-custom-fields/-1

**Comment by laoneo** [comment]
I can't reproduce the issue. Can you describe the steps to get the error?

**Comment by brianteeman** [comment]
I think it might have been my repo. I will check again in the morning and
close if necessary

**Comment by brianteeman** [comment]
Rechecked and must have been something in my repo
