### ISSUE TITLE
Hide/Show sidebar menu items

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/custom-fields#87]
As discussed at JAB16 it would be great if there was an option in the component configuration to hide the two fields sidebar menu items.

**Comment by laoneo** [comment]
Under which tab do you expect them?

**Comment by brianteeman** [comment]
Not really sure - perhaps under its own tab

**Comment by laoneo** [comment]
I would suggest then "Integration".

**Comment by brianteeman** [comment]
that works for me

On 31 May 2016 at 07:25, Allon Moritz notifications@github.com wrote:

> I would suggest then "Integration".
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/87#issuecomment-222602344,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8WlGr02-B8eCuhkk5GlBoQPxY8zJks5qG9RegaJpZM4Ijyi6
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
