### ISSUE TITLE
Is this colon really expected and should be hard coded?

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/custom-fields#9]
see: https://github.com/joomla-projects/custom-fields/blob/custom-fields/components/com_fields/layouts/field/render.php#L28

I'm not sure if we should realy hardcode that colon but maybe there is a reason for it ;)

**Comment by laoneo** [comment]
The label is meant to be displayed there, what else you want render as label?

**Comment by zero-24** [comment]
Hi,
I don't speak about the label but bevor the closing span tag there is a : And i'm not sure if that is expected ;)

**Comment by laoneo** [comment]
It looks better integrated into articles:

![image](https://cloud.githubusercontent.com/assets/251072/14201910/38acde08-f7f5-11e5-8812-3730e284042d.png)

Any suggestion it should look like for you?

**Comment by zero-24** [comment]
Ok. That looks ok from here :) Thanks
