### ISSUE TITLE
Category assignment and creation for custom fields

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#91]
In Joomla all articles and contacts (...) which have no category are assigned to "Uncategorised".
IMO the custom fields should follow this logic.
And also allow to create the category on the fly as it´s a new feature for articles, contacts, newsfeed and banner in 3.6

**Comment by laoneo** [comment]
There is no category needed. It is up to the developer if she/he wants to support field groups. So there is no reason to create extra categories when they are not needed.

**Comment by coolcat-creations** [comment]
Is the proper name then maybe "field groups" instead of "field category"?
