### ISSUE TITLE
Feedback: Custom fields in first tab?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#93]
From enduser view i would rather like to have the custom fields already in the first tab / content tab. 
By using them often it will annoy me to always have to switch the tab?
What do you think about it ?

**Comment by brianteeman** [comment]
How would you deal with the fact that you can have multiple tabs (groups) of custom fields?

**Comment by coolcat-creations** [comment]
Good point...!

**Comment by laoneo** [comment]
Some users of DPFields did it with layout overrides, because they did know exactly what for fields they wanted to show on the first tab.

**Comment by laoneo** [comment]
But it is not the first request I got, having some fields available on the first tab. At the moment there is no out of the box way in com_content. What can work is a new setting on the field like "primary" which will then be shown on the first tab. What you guys think?

**Comment by coolcat-creations** [comment]
A primary option would be great! or  assigning a whole field category to be primary and it appears then below the standard ?

**Comment by brianteeman** [comment]
Technically that is possible but then where on the page would the fields
appear?

On 1 June 2016 at 14:16, designbengel notifications@github.com wrote:

> A primary option would be great! or assigning a whole field category to be
> primary and it appears then below the standard ?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/93#issuecomment-222988679,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8VkWxYz69f92eVXH8ADJ_XBLd9anks5qHYY0gaJpZM4IpIS1
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by coolcat-creations** [comment]
I´d put them below the editorfield, but by testing i just had the idea what if it´s just possible to define the order of the tabs? 

For example i´m using a CCK to have my customer upload 1) Monthly Promotions (Just title-field and upload-field), 2) Slideshow Images (Just image upload field) 3) Items to show on a map. (Name, Adress, Logo, Lang, Lat) - They actually don´t need any other field beside this. (no wysiwyg, no article options)

So what if i could check a field-group to be at the first tab? 

Good / Bad idea?

**Comment by skelgaard** [comment]
Again as said before, thats what some sort of layout overwrite method would be nice to put in where you could do some simple html setup like 
< div class="field1">{field1_id}</ div>< div>{maincontent}</ div>< div class="field2">{field2_id}</ div> 
or something like that, that could be assigned to a category or some other way, so that you could custom the way ppl need to input content on the different categories

**Comment by laoneo** [comment]
@skelgaard this issue is about a different topic. It's about the placement in a form and not for rendering.

**Comment by skelgaard** [comment]
@laoneo place/render in admin edit view is in my eyes the same thing or am i not speaking same language as you are ? do i need to make drawings for you ?

**Comment by laoneo** [comment]
If you want to render a field, then you don't need some templating functionality at all. $form->renderField('field-alias'); does the job.

**Comment by skelgaard** [comment]
yes but i still can't do a template per category on how to display the edit fields

**Comment by laoneo** [comment]
But this issue is about a different topic. If you want to do some templating for form rendering then please open a new PR against this repo with your suggestion as I can just imagine what you have in mind.
Thanks for understanding.

**Comment by laoneo** [comment]
There is also another problem which can happen. Having one layout which adds all the primary fields would mean then that the fields are rendered all in one place. Means you will have then no option to say, I want one field after the first image another after the title and the third one in the Options tab at the end. For me the primary option looks like it is only half backed. I guess how the form views are implemented right now there is no proper solution to implement your requirement.

**Comment by laoneo** [comment]
How should we proceed here? If there is a requirement to place input fields on different positions in a form, then an issue against the CSM repo should be opened (but I think there will be not much luck to implement it).

**Comment by ironrai** [comment]
Decide which fields will be in the first tab is very important, especially for very large sites with a high volume of content. 
It may sound exaggerated, but when you need to load large number of articles a day, having to click on another tab to load info substantially increases the time it takes

sorry for my bad english...

**Comment by ironrai** [comment]
after all, I think @laoneo is right, there are several problems to be solved before.

**Comment by laoneo** [comment]
The state of the tabs is saved, means when you need to edit the same field in a lot of articles the same tab will be opened again.

**Comment by laoneo** [comment]
I'm closing this issue as it would be a hack if we would add a special setting to show the fields on the first tab. From this discussion, the whole form rendering needs an overhaul.
