### ISSUE TITLE
UX Feedback: Field Description WYSIWYG 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#94]
Is there a reason why the field description is that big? I think it´s enough to have a textarea field with just 50 cols and about 3 rows like the comment field for modules. IMO it takes otherwise too much space and is distracting.

**Comment by brianteeman** [comment]
I "think" this is a limitation of the current joomla implementation of the wywiwyg field where the size is defined in the editor plugin (not fields) and cannot be customised

**Comment by coolcat-creations** [comment]
Yes but isn´t it just a comment field? Then i would choose a textarea field to appear there.

**Comment by brianteeman** [comment]
Yes I agree - its an internal field so doesnt need formatting etc

**Comment by laoneo** [comment]
The description is shown when you hover over the label of the field, when it is rendered in the form. IMO for the end user it is more convenient to have an editor instead of a textarea, because HTML is supported as field description.

**Comment by coolcat-creations** [comment]
I would name it tooltip-text then or something like that? For me this wasn´t clear...

**Comment by laoneo** [comment]
It was named description, because it is the description parameter in the generated XML string. Perhaps on a later point the description will be used for something else as well. It is also available in the layouts and inline content. So I would leave it description. But changing the tootltip of it, with a more clear message would improve the situation. What do you think?

**Comment by brianteeman** [comment]
Thats an option. One concern is that with it being a wysiwyg editor a user
may think they can add images and links in there which sill not work in a
tooltip

On 2 June 2016 at 07:07, Allon Moritz notifications@github.com wrote:

> It was named description, because it is the description parameter in the
> generated XML string. Perhaps on a later point the description will be used
> for something else as well. It is also available in the layouts and inline
> content. So I would leave it description. But changing the tootltip of it,
> with a more clear message would improve the situation. What do you think?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/94#issuecomment-223203563,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8Yi9yKaigaaTjb1F1Dj3IE-28HKUks5qHnMGgaJpZM4IpIZ8
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
They will be displayed. Clicking on a link is not possible because the popup disappears. But that's only because no delay is set.

**Comment by brianteeman** [comment]
The point is that the wysiwyg lets the user think they can do something
which they cant (at least not effectively)

On 2 June 2016 at 09:08, Allon Moritz notifications@github.com wrote:

> They will be displayed. Clicking on a link is not possible because the
> popup disappears. But that's only because no delay is set.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/94#issuecomment-223223829,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8U_5tdt93ubZaKnzq63NIGjXIFKDks5qHo9lgaJpZM4IpIZ8
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
But in this case it counts more to give the user an editor where quickly some nice formated text can be written instead of having the fear that some not allowed stuff will be done. We are talking here about the description of a tooltip which is done by the site admin with back end access and not users who want to crash the site.

**Comment by brianteeman** [comment]
To quote from my client yesterday
"Why do you give me the ability to do something that I should not or cannot
do"

On 2 June 2016 at 10:20, Allon Moritz notifications@github.com wrote:

> But in this case it counts more to give the user an editor where quickly
> some nice formated text can be written instead of having the fear that some
> not allowed stuff will be done. We are talking here about the description
> of a tooltip which is done by the site admin with back end access and not
> users who want to crash the site.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/94#issuecomment-223239590,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8RfN2cVNSweL-3XoHZMTTawapAj1ks5qHqBzgaJpZM4IpIZ8
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by laoneo** [comment]
> Why do you give me the ability to do something that I should not or cannot do

It does not mean the person should not or cannot do it. If the intention is there from a site admin to do franky things then she/he can do it also with a textarea.

**Comment by brianteeman** [comment]
I give up

**Comment by laoneo** [comment]
Ok, closing.
