### ISSUE TITLE
Error when path doesn´t exist: JFolder: :files: Path is not a folder. 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#97]
#### Steps to reproduce the issue

1) Create an image field with an (yet) non existing path inside the image folder
2) Try to edit an Article
#### Expected result
- A component i´m using creates the folder if it doesn´t exist.
- Other possibility would be to have a directory listing for letting the user chose the directory
#### Actual result

There is an error message when trying to edit an article:
JFolder: :files: Path is not a folder. Path: customfields/images/rezeptbilder
JFolder: :folder: Path is not a folder. Path: customfields/banners

**Comment by laoneo** [comment]
Can you please test the referenced PR that we can bring it into 3.6? Thanks.
