### ISSUE TITLE
Field description / Tooltip: Image not loaded

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/custom-fields#99]
#### Steps to reproduce the issue

Create a field and put an image in the description
#### Expected result

image should appear in the tooltip
#### Actual result

Imagelink is broken.

**Comment by laoneo** [comment]
I had a look on it. The problem is that the path is relative in the description. If you open the article on the front then the image shows up in the tooltip. It is not correct on the back end only.

**Comment by coolcat-creations** [comment]
So i would remove the wysiwyg option from that field, and make it much smaller as suggested. its not neccessary anyway IMO... Its just a tooltip text ~~

**Comment by laoneo** [comment]
It is not related to the editor, you will have the same problem with a text field as well.

**Comment by coolcat-creations** [comment]
With Textarea you just include text no formatting and no images. So no issues then?

**Comment by laoneo** [comment]
As discussed here #94 , you can even input more harmfull stuff as it doesn't get cleaned up by the editor. You will have the same issue when insert HTML content in the textarea.

**Comment by coolcat-creations** [comment]
no, i meant a textarea without possibility to input html :-/

**Comment by laoneo** [comment]
Is it bad design to have HTML content in tooltips from UX perspective? If yes, then I will change it to a text area, stripping out any HTML. Slowly changing my mind. @brianteeman don't laugh 🙉 

Was reading this article http://uxfindings.blogspot.ch/2014/08/tooltip-best-practices.html?m=1. They state that tooltips should have short information with no clutter.

**Comment by brianteeman** [comment]
Avoid over-communication

Be explicit wherever necessary but don't explain the obvious. On the web
scanning is the norm and too much text weakens the effectiveness of the
message - it does not enhance it.

On 4 June 2016 at 17:44, Allon Moritz notifications@github.com wrote:

> Is it bad design to have HTML content in tooltips from UX perspective? If
> yes, then I will change it to a text area, stripping out any HTML. Slowly
> changing my mind. @brianteeman https://github.com/brianteeman don't
> laugh 🙉
> 
> Was reading this article
> http://uxfindings.blogspot.ch/2014/08/tooltip-best-practices.html?m=1.
> They state that tooltips should have short information with no clutter.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/custom-fields/issues/99#issuecomment-223765576,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8W4esQ1h6px3Pl-H1JGV-bOc3E83ks5qIauEgaJpZM4Ir26-
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
